### ISSUE TITLE
required function is not working in "to-words.js" file

### ISSUE THREAD

**Issue by Rahul2pancholi** [mastermunj/to-words#182]
ERROR : - Error: Unknown Locale "en-IN"

Referenced link : https://github.com/facebook/react-native/issues/6391

**Comment by mastermunj** [comment]
Hi @Rahul2pancholi, I have moved to static require using switch case for importing locale.

It's available in branch named `static-require`.

Please help test it if possible.

**Comment by vibhorpahare** [comment]
I have also used the same switch case as a workaround
Any reason why haven't you have pushed it in the master branch..?

**Comment by mastermunj** [comment]
No apparent reason. I preferred the dynamic import way, however, it seems that may be problem with React.

I will merge it in main branch and do a release today.
