### ISSUE TITLE
Myanmar Kyats(MMK) not supporting 

### ISSUE THREAD

**Issue by kavuruchandini52** [mastermunj/to-words#249]
I have tired MMK , but this to-words package is not supporting MMK, pls add this MMK currency also for this package 

  ex: when we giving amount as 887.00 in digit  

     it should convert like : -  eight hundred eighty seven Kyats only

**Comment by mastermunj** [comment]
Hi @kavuruchandini52 I do not have idea about how MMK works. I'd request you to raise PR for needed changes.

**Comment by kavuruchandini52** [comment]
hi @mastermunj  i sending u the example formats

 example 1:  if we give amount as : 12345.00 we can convert amount as 

 INR => tweleve thousand three hundred fourty five rupees only
MUR => tweleve thousand three hundred fourty five dollars only

likewise for MMK 
 
MMK  =>  tweleve thousand three hundred fourty five Kyats only

 
example 2:  if we give amount as 15353.6 we can convert amount as

INR =>  Fifteen thousand three hundred fifty three rupees and six paisa only

likewise for MMK

 MMK => Fifteen thousand three hundred fifty three Kyats and six pyas only

**Comment by mastermunj** [comment]
Please review [en-IN.ts](https://github.com/mastermunj/to-words/blob/master/src/locales/en-IN.ts) and [en-IN.test.ts](https://github.com/mastermunj/to-words/blob/master/__tests__/en-IN.test.ts) files to confirm if following will be correct or incorrect.

* Replace `Rupee` with `Kyat`
* Replace `Rupees` with `Kyats`
* Replace `Paisa` with `Pya`
* Replace `Paise` with `Pyas`
* Replace `₹` with `K`

Please also confirm [NumberToWordsMapping](https://github.com/mastermunj/to-words/blob/master/src/locales/en-IN.ts#L22) will be exactly same for Myanmar way of numerical?

**Comment by kavuruchandini52** [comment]
Hi @mastermunj  the above commet is correct , NumberToWordsMapping will be exactly same for myanmar and numerical .

Replace Rupee with Kyat
Replace Rupees with Kyats
Replace Paisa with Pya
Replace Paise with Pyas
Replace ₹ with K 

is correct

**Comment by mastermunj** [comment]
@kavuruchandini52 Please check #253 for implementation. If it works well, will do release for it.

**Comment by kavuruchandini52** [comment]
hi @mastermunj  , it will work, pls do release for it

**Comment by mastermunj** [comment]
Released v2.3.0
