### ISSUE TITLE
 MMK does n't support Crore (number in words)

### ISSUE THREAD

**Issue by kavuruchandini52** [mastermunj/to-words#261]
Hi @mastermunj  mmk does not support crore pls replace crore with million

ex:     public numberwordsMapping = [ 

                      {number:1000000, value: 'Million'},
                     {number: 100000,value:'Lakh'},
                     {number: 1000, value: 'Thousand'},
                    {number:100,value:'hundred'},
                    {number :10,value:'Ten'}
];

**Comment by mastermunj** [comment]
@kavuruchandini52 A little occupied with work, will try to cover it later. Meanwhile, if you can raise a PR, happy to review it.

**Comment by kavuruchandini52** [comment]
Hi @mastermunj  u take time but pls update once u done thanks for reply

**Comment by kavuruchandini52** [comment]
Hi @mastermunj  can u please take it as priority it is needful or can u please tell me ETA

**Comment by kavuruchandini52** [comment]
hi @mastermunj  do u need any info u can ask me , pls take it as prioritized  MMK client confirm the correct format for MMK

**Comment by gyannitrr1993** [comment]
Hi @mastermunj can you please update on the above request, if you need any clarification please mention here

**Comment by gyannitrr1993** [comment]
Hi @mastermunj this how the number system for international currency,

In international system

1-Ones

10-Tens

100-Hundred

1000-Thousand

10,000-Ten thousand

100,000-Hundred thousand

1,000,000-Million

10,000,000-Ten Million

100,000,000-Hundred million

1,000,000,000-Billion

10,000,000,000-Ten Billion

So you can choose your values

**Comment by mastermunj** [comment]
@kavuruchandini52 @gyannitrr1993 I worked on MMK locale based on confirmation provided [here](https://github.com/mastermunj/to-words/issues/249#issuecomment-730846929).

Are you suggesting that the number system needs to change to use Millions instead of Crores?

Kindly review the number system for en-US and let me know if that is one to be used? If it's different altogether, I'd need you to list whole mapping to make it simpler and easier.

**Comment by kavuruchandini52** [comment]
hi @mastermunj en-US  number system and en-MM number system is same , u have to upadte the number system for en-MM
![image](https://user-images.githubusercontent.com/74708197/101309893-73324180-3873-11eb-9d18-ba5db895affe.png)

**Comment by mastermunj** [comment]
@kavuruchandini52 and @gyannitrr1993 Please check #265 and confirm if it's working as expected.

**Comment by kavuruchandini52** [comment]
Hi @mastermunj  i have gone through the files u modified and it's correct pls release the new version and upadte here

**Comment by mastermunj** [comment]
Release v2.3.1 with fix.
