### ISSUE TITLE
Have a roadmap to reduce package size

### ISSUE THREAD

**Issue by adarshmadrecha** [mastermunj/to-words#312]
With every new release, the size of the package is increasing.
Have a road map to manage this size.

![image](https://user-images.githubusercontent.com/11911938/105565349-559a3800-5d4c-11eb-8f27-621c1b258cba.png)

Image Reference: https://bundlephobia.com/result?p=to-words@2.3.1

**Comment by mastermunj** [comment]
Thank you @adarshmadrecha for insights. Any suggestions do you have on how the size of the package can be managed well?

**Comment by mastermunj** [comment]
Closing as non-actionable.
