### ISSUE TITLE
In case of indian numbering system for 1100 converted currency showing thousand hundred instead of thousand one hundred.

### ISSUE THREAD

**Issue by shwethats** [mastermunj/to-words#444]

**Comment by mastermunj** [comment]
Thanks for reporting. I have started work on V3 that will allow more flexibility, one of them being able to have word conversion marked for exact matches, that should solve this problem.

**Comment by mastermunj** [comment]
@shwethats Please try v3 alpha where this issue is fixed and share your feedback.

Try
```sh
npm i to-words@3.0.0-alpha.0
```

**Comment by mastermunj** [comment]
Resolved in v3.0.0
