### ISSUE TITLE
How can i remove only?

### ISSUE THREAD

**Issue by vn93ksatria** [mastermunj/to-words#448]
Hi @mastermunj  thanks for this plugin, but can you help me on how i disable the 'ONLY' words

Thanks

**Comment by mastermunj** [comment]
Sorry, as of now there is no way to do it except that you can do string replace after conversion.

**Comment by mastermunj** [comment]
@vn93ksatria Please try v3 alpha that has provision to not add `only` when the currency option is set to true.

Try
```sh
npm i to-words@3.0.0-alpha.0
```

You can read the option details [here](https://github.com/mastermunj/to-words/blob/v3/README.md#options).
