### ISSUE TITLE
Add Support for Ghana Locale

### ISSUE THREAD

**Issue by wocodes** [mastermunj/to-words#516]
Hi, I'm super happy there is support for the Nigerian currency as I'm Nigerian but in my project I currently support users in Ghana and as such I'd love to have this support. I code in Javascript and have little to no knowledge of Typescript else, I'd love to contribute this

**Comment by mastermunj** [comment]
Hi @wocodes, sure, I'd appreciate you contributing.

If you know javascript, you should be able to easily contribute. Have a look at https://github.com/mastermunj/to-words/blob/master/src/locales/en-NG.ts and try to create similar file with the locale you'd like to contribute for.

In nutshell you will need to create files in
* src/locales/[locale].ts
* __tests__/[locale].test.ts

Include your file in the loop by modifying:
* getLocaleClass in https://github.com/mastermunj/to-words/blob/master/src/to-words.ts#L38
* Supported Locale in https://github.com/mastermunj/to-words/blob/master/README.md#supported-locale

That's about it. Once you raise a PR, I will help you ahead.

**Comment by mastermunj** [comment]
Handled in #517. Thank you @wocodes
