### ISSUE TITLE
Need Support for localeCode 

### ISSUE THREAD

**Issue by gyannitrr1993** [mastermunj/to-words#55]
Currently only en-IN & en-US are supported.
We need to use and support more locale Code.

**Comment by mastermunj** [comment]
Which other locale do you need support for?

**Comment by gyannitrr1993** [comment]
I need to use for Australian Dollar => en-AU and Mauritian rupee => en-MU.

**Comment by mastermunj** [comment]
is there any difference in output between en-US <> en-AU and en-MU <> en-IN?

Can you point me towards how both currencies write numbers to words?

**Comment by gyannitrr1993** [comment]
For Example:
20240.45
MUR => (en-MU) "Twenty Thousand Two Hundred Forty Rupees And Forty Five Cents Only"
INR   => (en-INR) "Twenty Thousand Two Hundred Forty Rupees And Forty Five Paise Only"
USD => (en-US)    "Twenty Thousand Two Hundred Forty Dollars And Forty Five Cents Only"
AUD => (en-AU)  "Twenty Thousand Two Hundred Forty Dollars And Forty Five Cents Only"

USD and AUD are same, but INR and MUR are different,
So I need to use MUR as I have given above.

**Comment by mastermunj** [comment]
If my understanding is right, the difference between en-IN & en-MU are:

- Paisa <> Cent
- Paise <> Cents
- Symbol ₹ <> Rs

Did I miss any other difference?

Also, I believe en-US can be used for en-AU without any issue. Correct?

**Comment by gyannitrr1993** [comment]
Hi, 
20240.45
I want to use for MUR, the expected Result as below should come:
MUR => (en-MU) "Twenty Thousand Two Hundred Forty Rupees And Forty Five Cents Only"

but If I use below one for MUR both are Different
USD => (en-US) "Twenty Thousand Two Hundred Forty Dollars And Forty Five Cents Only"

can you see all four examples where for MUR I am not getting the expected result, if I paas:
INR => (en-INR) "Twenty Thousand Two Hundred Forty Rupees And Forty Five Paise Only"
USD => (en-US) "Twenty Thousand Two Hundred Forty Dollars And Forty Five Cents Only"

but I want:
MUR => (en-MU) "Twenty Thousand Two Hundred Forty Rupees And Forty Five Cents Only"

**Comment by gyannitrr1993** [comment]
![DIFF](https://user-images.githubusercontent.com/42031651/85140402-d77c2d00-b262-11ea-9bdf-7a27cf454b52.PNG)

**Comment by mastermunj** [comment]
Thank you for confirming the changes @gyannitrr1993 

I am not sure if Mauritius follows Lakhs & Crores as standard or Millions & Billions.

Would you have any reference to confirm this?

**Comment by gyannitrr1993** [comment]
The Only Difference between INR and MUR is:
INR - Paise (for paise)
MUR - Cents (for paise)

please check here, what we called Paisa in MUR: 
https://mauritiusattractions.com/mauritius-currency-i-92.html
![MUR](https://user-images.githubusercontent.com/42031651/85141230-1494ef00-b264-11ea-80e6-da935220c7ff.PNG)

**Comment by gyannitrr1993** [comment]
![MUR1](https://user-images.githubusercontent.com/42031651/85141611-a866bb00-b264-11ea-9a34-389ae122cb64.PNG)

**Comment by mastermunj** [comment]
#56 should solve this. Can you do a quick check if it really solves for you?

**Comment by gyannitrr1993** [comment]
Sure thankyou, I will check.

**Comment by gyannitrr1993** [comment]
Yes, It will solve my requirement.

**Comment by mastermunj** [comment]
Released a new version 2.2.0 that solves this.

**Comment by gyannitrr1993** [comment]
I am trying to use localeCode 'en-MU', I have updated my package 2.2.0

![image](https://user-images.githubusercontent.com/42031651/85195745-b236ff80-b2f2-11ea-8cca-a24e9fc55871.png)
