### ISSUE TITLE
localeCode for 'en-MU' not working for me

### ISSUE THREAD

**Issue by gyannitrr1993** [mastermunj/to-words#58]
I have updated my package "to-words": "^2.2.0", I getting below error
![image](https://user-images.githubusercontent.com/42031651/85195784-fcb87c00-b2f2-11ea-9623-094f602612e4.png)

**Comment by mastermunj** [comment]
Sorry, @gyannitrr1993 for the mess up. I did not build before releasing it.

I have release 2.2.1 that should solve the problem.

I will also work towards automating this for future releases to avoid such a problem.

**Comment by gyannitrr1993** [comment]
thanks, working fine now!!
