### ISSUE TITLE
getting warning on build of code

### ISSUE THREAD

**Issue by gyannitrr1993** [mastermunj/to-words#63]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/42031651/85269778-ff9fa200-b495-11ea-96b3-478f37311e4a.png)

please see the attached screenshot

**Comment by mastermunj** [comment]
Please help with steps to replicate, if possible, with a repo for easy replication.

Moreover, shouldn't node_modules be excluded from your current build tasks?

**Comment by gyannitrr1993** [comment]
Hi, 
We are including this in a angular project and in angular compilation this warning is coming
on angular ng serve this warning is coming

**Comment by mastermunj** [comment]
Please help with a repo that replicates the issue. I will look into resolving it.

**Comment by gyannitrr1993** [comment]
Hi,

I have checked in new repo and there i am not getting any warning after adding to-words. Thanks for you support.
