### ISSUE TITLE
Getting Error while compiling: '/to-words/src/types.ts (14,17): error TS2304: Cannot find name 'unknown''

### ISSUE THREAD

**Issue by kushagra-goenka** [mastermunj/to-words#836]
Getting Error while compiling: '/to-words/src/types.ts (14,17): error TS2304: Cannot find name 'unknown'

**Comment by mastermunj** [comment]
Can you help in reproducing the error? I am unable to reproduce this error.

**Comment by mastermunj** [comment]
Closing since there is no response to the query.
