### ISSUE TITLE
Indian Numbering Systems

### ISSUE THREAD

**Issue by MohsenAlyafei** [mastermunj/to-words#89]
Regarding the conversion into words under the Indian Numbering System, in general, could you assist on this, please : https://stackoverflow.com/questions/62795243/indian-numbering-system-how-to-convert-into-the-official-and-common-use-numberi

**Comment by mastermunj** [comment]
@MohsenAlyafei I'd request you to be more specific about what do you expect help with.

**Comment by mastermunj** [comment]
Closing as non-actionable.
